forum/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<post_id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^new_post/$', views.new_post, name='new_post'),
    url(r'^edit_post/(?P<post_id>\d+)/$', views.edit_post, name='edit_post'),
    url(r'^post/like/$', views.post_like, name='post_like'),
]

xiaohaishi04/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

import notifications.urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('forum.urls', namespace='forum', app_name='forum')),
    url(r'^users/', include('users.urls', namespace='users', app_name='users')),
    url(r'^comment/', include('two_comment.urls', namespace='two_comment', app_name='two_comment')),
    url(r'^notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^confession/', include('confession_wall.urls', namespace='confession_wall', app_name='confession_wall')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse


class Post(models.Model):
    title = models.CharField(max_length=128, blank=True, verbose_name='标题', default='无标题')
    body = models.TextField(verbose_name='内容')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='forum_posts')
    user_like = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                       related_name='posts_liked',
                                       blank=True)
    total_like = models.PositiveIntegerField(default=0, db_index=True)
    view_count = models.PositiveIntegerField(default=0, verbose_name='查看次数')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = '文章'
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('forum:post_detail', args=[self.id])

    def get_summary(self):
        return self.body[:60]

    def view_count_increase(self):
        self.view_count += 1
        self.save(update_fields=['view_count'])

forum/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'body',)

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse, Http404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST

from actions.utils import create_action

from .models import Post
from .forms import PostForm


def post_list(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 8)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        posts = paginator.page(paginator.num_pages)
    if request.is_ajax():
        return render(request,
                      'forum/post/list_ajax.html',
                      {'posts': posts})
    return render(request,
                  'forum/post/list.html',
                  {'posts': posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.view_count_increase()
    return render(request,
                  'forum/post/detail.html',
                  {'post': post})


@login_required
def new_post(request):
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            create_action(request.user, 'new_post', new_post)
            return HttpResponseRedirect(reverse('forum:post_list'))
    return render(request, 'forum/post/new.html', {'form': form})


@login_required
@require_POST
def post_like(request):
    post_id = request.POST.get('id')
    action = request.POST.get('action')
    if post_id and action:
        try:
            post = Post.objects.get(id=post_id)
            if action == 'like':
                post.user_like.add(request.user)
                create_action(request.user, 'like', post)
            else:
                post.user_like.remove(request.user)
            return JsonResponse({'msg': 'ok'})
        except Post.DoesNotExist:
            return JsonResponse({'msg': 'ko'})
    return JsonResponse({'msg': 'ko'})


@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        raise Http404
    if request.method != 'POST':
        form = PostForm(instance=post)
    else:
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile', args=[post.author.id]))

    context = {'post': post, 'form': form}
    return render(request, 'forum/post/edit_post.html', context)

forum/templates/forum/post/detail.html
{% extends "base.html" %}
{% load custom_markdown %}
{% load staticfiles %}

{% block header %}
    <h2>{{ post.title }}</h2>
    {% if post.author.nickname %}
        <span>{{ post.author.nickname }}</span>
    {% else %}
        <span>{{ post.author.username }}</span>
    {% endif %}
    <span>{{ post.created }}</span>
{% endblock %}

{% block content %}
    {{ post.body|custom_markdown }}
    <h5 class="page-header"></h5>
    {% with total_likes=post.user_like.count users_like=post.user_like.all %}
        <div>
            <a class="btn btn-default heart {% if request.user.is_authenticated %}{% else %}no-login{% endif %} " data-id="{{ post.id }}",
               data-action="{% if request.user in users_like %}un{% endif %}like"
               {% if request.user in users_like %}style="background-color: rgb(212, 106, 64); color: white"{% endif %} >
                <span class="glyphicon glyphicon-heart"></span>
                <span class="count">{{ total_likes }}</span>
            </a>
            <div class="share pull-right">
                <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a><a href="#" class="bds_sqq" data-cmd="sqq" title="分享到QQ好友"></a><a href="#" class="bds_douban" data-cmd="douban" title="分享到豆瓣网"></a></div>
                <script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"24"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
            </div>
        </div>
        <div id="comment-anchor">
            {% include 'two_comment/comment_list.html' with entry=post %}
        </div>

    {% endwith %}

    <style type="text/css">
        .heart{
            padding-top: 10px;
            border: 1px solid #EA6F5A;
            border-radius: 40px;
        }
    </style>
{#    <script>#}
{#        $(window).load(function () {#}
{#            alert(sessionStorage.getItem('comment_anchor'));#}
{#             if (sessionStorage.getItem('anchor')){#}
{#                var offtop = sessionStorage.getItem('comment_anchor');#}
{#                (document).scrollTop(offtop);#}
{#                sessionStorage.removeItem('anchor');#}
{#            }#}
{#        });#}
{#    </script>#}
{% endblock %}



{% block domready %}
    $("a.heart").click(function (e) {
        e.preventDefault();
        $this = $(this);
        if($this.hasClass('no-login')){
            alert("请在登陆后执行该操作");
            return false;
        }
        var id = $this.data('id');
        var action = $this.data('action');

        $.post('{% url 'forum:post_like' %}',{
            id: id,
            action: action
        }, function (data) {

            if (data['msg'] == 'ok'){
                $this.data('action', action == 'like' ? 'unlike' : 'like');
                var previous_likes = parseInt($('span.count').text());
                if (action == 'like'){
                    $this.attr("style","background-color: rgb(212, 106, 64); color: white");
                    $this.find("span.count").text(previous_likes + 1);
                }else if (action == 'unlike'){
                    $this.attr("style","");
                    $this.find("span.count").text(previous_likes - 1);
                }
            }
        });
    });
{% endblock %}

forum/templates/forum/post/edit_post.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h3>
        <a href="{{ post.author.get_absolute_url }}">我的主页</a> - 编辑文章
    </h3>
{% endblock %}

{% block content %}
    <form action="{% url 'forum:edit_post' post.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit">保存更改</button>
        {% endbuttons %}
    </form>
{% endblock %}

forum/templates/forum/post/list.html
{% extends "base.html" %}
{% load forum_tags %}

{% block header %}
   <blockquote>
        <h3>崇德尚学，求实创新。</h3>
    </blockquote>
{% endblock %}

{% block content %}
        <ul class="list-group note-list post_list ">
            {% include "forum/post/list_ajax.html" %}
        </ul>
    <style type="text/css">
        .note-list li{
            margin: 0 0 17px;
            padding: 0 2px 17px 0;
            border-bottom: 1px solid #f0f0f0;
            word-wrap: break-word;
        }
        .note-list-item .title{
            margin: -7px 0 4px;
            display: inherit;
            font-size: 18px;
            font-weight: 700;
            line-height: 1.5;
        }
        .note-list-item .author{
            margin-bottom: 14px;
            font-size: 13px;
        }
         .note-list-item .abstract{
            line-height: 24px;
        }

        .note-list-item{
            border: none;
        }
        .note-list blockquote{
            margin-bottom: 0;
            color: #969696;
            border-left: 3px solid #d9d9d9;
        }
        .info{
            display: inline-block;
            vertical-align: middle;
            line-height: normal;
            padding-left: 5px;
        }
        .meta{
            padding-top: 2px;
            font-size: 12px;
            color: #969696;
            line-height: normal;
        }
    </style>


{#    <script>#}
{#       $(document).ready(function () {#}
{#           $('.comment-count').click(function () {#}
{#               var comment_anchor = "#comment-anchor";#}
{#               sessionStorage.setItem('anchor', true);#}
{#               sessionStorage.setItem('comment_anchor', comment_anchor);#}
{#           });#}
{#       });#}
{#    </script>#}
{% endblock %}

{% block sidebar %}
     <div class="list-group">
         {% get_most_popular_post as poplular_post_list %}
         <a class="list-group-item list-group-item-danger"><h5>最受欢迎文章</h5></a>
         {% for post in poplular_post_list %}
             <a href="{{ post.get_absolute_url }}" class="list-group-item">
                 <span class="badge" style="background-color: #EA6F5A">
                     <span style="color: #f6feff" class="glyphicon glyphicon-heart"></span>
                     <span>{{ post.total_like }}</span>
                 </span>
                 {{ post.title }}
             </a>
         {% empty %}
             <a class="list-group-item">暂时没有排行</a>
         {% endfor %}
     </div>
{% endblock %}


{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;

    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height() - 200;
        if  ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
            block_request = true;
            page += 1;
            $.get('?page=' + page, function(data) {
                if(data == '')
                {
                    empty_page = true;
                }
                else {
                    block_request = false;
                    $('.post_list').append(data);
                }
            });
        }
    });
{% endblock %}

forum/templates/forum/post/list_ajax.html
{% load custom_filter %}


{% for post in posts %}
    {% with total_likes=post.user_like.count users_like=post.user_like.all view_count=post.view_count %}
        <li class="list-group-item  note-list-item">
            <div class="content">
                <div class="author">
                        <a class="avatar " href="{{ post.author.get_absolute_url }}">
                            <img class="img-circle carousel-inne" src="{{ post.author.avatar.url }}" alt="头像" style="height: 32px; width: 32px">
                        </a>
                        <div class="info">
                            <a href="{{ post.author.get_absolute_url }}">
                                {% if post.author.nickname %}
                                    {{ post.author.nickname }}
                                {% else %}
                                    {{ post.author.username }}
                                {% endif %}
                            </a>
                            <span class="time" style="margin-left: 3px">{{ post.created|timesince }}前</span>
                        </div>
                    </div>
                <a class="title"  href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                <p class="abstract">{{ post.body|remove_markdown|truncatechars:128}}</p>
                <div class="meta">
                    <span class="glyphicon glyphicon-eye-open"></span>
                    <span>{{ view_count }}</span>
                    <span style="margin-left: 10px">
                        <a href="{{ post.get_absolute_url }}" style="color: #969696;" class="comment-count">
                            <span  class="glyphicon glyphicon-comment"></span>
                            <span>{{ post.entry_comments.count }}</span>
                        </a>
                    </span>

                    <span style="margin-left: 10px" class="glyphicon glyphicon-heart"></span>
                    <span>{{ total_likes }}</span>
                </div>
            </div>
        </li>
    {% endwith %}
{% endfor %}

forum/templates/forum/post/new.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>写文章</h2>
{% endblock %}

{% block content %} 
   <form action="{% url 'forum:new_post' %}" method='post' class="form">

    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">发布</button>
    {% endbuttons %}

  </form>
{% endblock %}

{% block sidebar %}
    <h3>编辑器支持 Markdown</h3>
    <a href="http://md.ityouknow.com/">一分钟快速学会使用Markdown</a>

{% endblock %}