forum/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<post_id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^new_post/$', views.new_post, name='new_post'),
    url(r'^edit_post/(?P<post_id>\d+)/$', views.edit_post, name='edit_post'),
    url(r'^post/like/$', views.post_like, name='post_like'),
]

two_comment/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^entry/$', views.submit_comment, name='submit_comment'),
    url(r'^reply/$', views.submit_reply, name='submit_reply'),
    url(r'^favour/$', views.submit_favour, name='submit_favour'),
]

xiaohaishi04/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

import notifications.urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('forum.urls', namespace='forum', app_name='forum')),
    url(r'^users/', include('users.urls', namespace='users', app_name='users')),
    url(r'^comment/', include('two_comment.urls', namespace='two_comment', app_name='two_comment')),
    url(r'^notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^confession/', include('confession_wall.urls', namespace='confession_wall', app_name='confession_wall')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

two_comment/models.py
from django.db import models
from django.conf import settings

"""
    这里可以直接在settings里设置要评论的条目和所属作者
    比如我的项目里的是：
    # 自定义用户model
    AUTH_USER_MODEL = 'users.user'
    # two comments settings
    COMMENT_ENTRY_MODEL = 'forum.post'
"""


class Comment(models.Model):
    entry = models.ForeignKey(settings.COMMENT_ENTRY_MODEL, related_name='entry_comments')
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_comments', blank=True, null=True)
    user_favour = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='comment_favour', blank=True)
    submit_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['submit_date']

    def __str__(self):
        return '%s 评论了 %s' % (self.author.username, self.entry)


class CommentReply(models.Model):
    comment = models.ForeignKey(Comment, related_name='comment_reply', blank=True, null=True)
    content = models.TextField()
    author_from = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_reply', blank=True, null=True)
    author_to = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True)
    submit_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['submit_date']

    def __str__(self):
        return '%s @ %s ' % (self.author_from.username, self.author_to.username)

two_comment/forms.py
from django import forms

from .models import Comment, CommentReply


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {'content': ''}
        widgets = {'content': forms.Textarea(attrs={'rows': 3, 'placeholder': '写下你的评论...'})}


class ReplyForm(forms.ModelForm):
    class Meta:
        model = CommentReply
        fields = ['content']
        labels = {'content': ''}
        widgets = {'content': forms.Textarea(attrs={'rows': 3, 'placeholder': '写下你的评论...'})}

two_comment/views.py
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse
from django.conf import settings
from django.apps import apps

from .models import Comment
from .forms import CommentForm, ReplyForm

from . import signals

"""
    这里解释下需要导入相关内容：
    login_required: 用来判断请求对象是否登入
    request_POST: 只能发起POST请求
    settings +  apps : 获取settings中设置的评论Entry，和所需User

"""


@login_required
@ require_POST
def submit_comment(request):
    """
    提交评论
    """
    entry_id = request.POST.get('id')
    app_model = settings.COMMENT_ENTRY_MODEL.split('.')
    Entry = apps.get_model(*app_model)
    if entry_id:
        try:
            entry = Entry.objects.get(id=entry_id)
            form = CommentForm(data=request.POST)
            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.entry = entry
                new_comment.author = request.user
                new_comment.save()
                new_comment_location = '#comment-' + str(new_comment.id)
                return JsonResponse({'status': 'ok', 'new_comment_location': new_comment_location})
        except Entry.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})


@login_required
@ require_POST
def submit_reply(request):
    """
    提交回复
    """
    comment_id = request.POST.get('comment_id')
    author_to_id = request.POST.get('author_to_id')
    app_model = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(*app_model)
    if comment_id and author_to_id:
        try:
            comment = Comment.objects.get(id=comment_id)
            author_to = User.objects.get(id=author_to_id)
            form = ReplyForm(data=request.POST)
            if form.is_valid():
                new_reply = form.save(commit=False)
                new_reply.comment = comment
                new_reply.author_from = request.user
                new_reply.author_to = author_to
                new_reply.save()
                return JsonResponse({'status': 'ok'})
        except Comment.DoesNotExist or User.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})


@login_required
@require_POST
def submit_favour(request):
    """
    提交点赞
    """
    comment_id = request.POST.get('id')
    action = request.POST.get('action')
    if comment_id and action:
        try:
            comment = Comment.objects.get(id=comment_id)
            if action == 'favour':
                comment.user_favour.add(request.user)
            else:
                comment.user_favour.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Comment.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})

two_comment/templates/two_comment/comment_list.html
{% load comment_tags %}
{% load bootstrap3 %}

<div class="comment-list" id="comment-list">
        {% get_comment_form as form %}
        <div>
            {% if request.user.is_authenticated %}
                <form class="new-comment" action=".">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="submit-function-block">
                        <a class="btn btn-success send pull-right" data-id="{{ entry.id }}" role="button">发送</a>
                        <a class="btn btn-default cancel pull-right" role="button">取消</a>
                    </div>
                 </form>
            {% else %}
                <div class="jumbotron no-reply">
                    <h4>登录后发布评论</h4>
                </div>
            {% endif %}
        </div>

        <div id="normal-comment-list" class="normal-comment-list">
            {% get_comment_list entry as comments %}
            {% if comments.count > 0 %}
                <div class="top-title">
                    <span>{{ comments.count }}</span>
                    <span>条评论</span>
                </div>
                {% for comment in comments %}
                    <div>
                        <div id="comment-{{ comment.id }}" class="comment">
                            <div>
                                <div class="author">
                                     <a class="avatar" href="{{ comment.author.get_absolute_url }}">
                                        <img class="img-circle carousel-inner" src="{{ comment.author.avatar.url }}" style="width: 38px; height: 38px;" >
                                    </a>
                                    <div class="info">
                                        <a href="{{ comment.author.get_absolute_url }}">
                                            <strong>
                                                {% if comment.author.nickname %}
                                                {{ comment.author.nickname }}
                                            {% else %}
                                                {{ comment.author.username }}
                                            {% endif %}
                                            </strong>
                                        </a>
                                        <div class="meta">
                                            <span>{{ comment.submit_date }}</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="comment-wrap">
                                    <p>{{ comment.content }}</p>
                                </div>
                                 <div class="tool-group">
                                 {% with users_favour=comment.user_favour.all %}
                                     <a class="favour-button {% if not request.user.is_authenticated %}no-login{% endif %}"
                                        data-id="{{ comment.id }}" data-action="{% if request.user in users_like %}dis{% endif %}favour"
                                        {% if request.user in users_favour %}style="color: #ea6f5a"{% endif %}>
                                         <span class="glyphicon glyphicon-thumbs-up"></span>
                                     </a>
                                     <small>赞</small>
                                 {% endwith %}
                                     <a class="reply-button {% if not request.user.is_authenticated %}no-login{% endif %}" data-to="{{ comment.author.id }}" data-comment="{{ comment.id }}">
                                        <small><span class="glyphicon glyphicon-comment"></span></small>
                                     </a>
                                     <small>回复</small>
                                 </div>
                            </div>

                        {% get_reply_list comment as replies %}
                            {% if replies %}
                                <div class="normal-reply-list">
                                {% for reply in replies %}
                                    <div id="reply-{{ reply.id }}" class="reply">
                                        <p>
                                           <span>
                                                <a href="{{ reply.author_from.get_absolute_url }}">{{ reply.author_from.username }}</a>:
                                           </span>
                                            <span>
                                                <a href="{{ reply.author_to.get_absolute_url }}">@{{ reply.author_to.username }}</a>
                                                {{ reply.content }}
                                            </span>
                                        </p>

                                        <div class="reply-tool-group">
                                            <span>{{ reply.submit_date }}</span>
                                            <a class="reply-button {% if not request.user.is_authenticated %}no-login{% endif %}" data-to="{{ comment.author.id }}" data-comment="{{ comment.id }}">
                                                <span class="glyphicon glyphicon-comment"></span>
                                            </a>
                                            <small>回复</small>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                                    <div class="reply-form">
                                        {% include 'two_comment/reply_form.html' %}
                                    </div>
                                </div>
                        </div>
                {% endfor %}
            {% else %}
                <div class="jumbotron no-reply">
                    <h4>暂无评论，来抢沙发</h4>
                </div>
            {% endif %}
            </div>
        </div>
</div>

        <style type="text/css">

            .author{
                margin-bottom: 15px;
            }
            .info{
                display: inline-block;
                vertical-align: middle;
                padding-left: 4px;
            }
            .meta{
                font-size: 12px;
                color: #969696;
            }
            .comment-list{
                padding-top: 20px;
            }
            .submit-function-block{
                display: none;
            }
            .cancel, .reply-cancel{
                margin-right: 18px;
            }

            .normal-comment-list{
                margin-top: 40px;
            }
            .top-title{
                padding-bottom: 18px;
                font-size: 17px;
                font-weight: 700;
                border-bottom: 1px solid #f0f0f0;
            }
             .comment{
                padding: 20px 0 30px;
                border-bottom: 1px solid #f0f0f0;
            }
            .normal-reply-list{
                margin-top: 20px;
                padding: 5px 0 5px 20px;
                border-left: 2px solid #d9d9d9;
            }
            .reply{
                margin-bottom: 15px;
                padding-bottom: 15px;
                border-bottom: 1px dashed #f0f0f0;
            }
            .reply-form{
                display: none;
            }
            .reply-tool-group{
                font-size: 12px;
                color: #969696;
            }
            .reply-button{
                margin-left: 10px;
                color: #969696;
            }
            .favour-button{
                color: #969696;
            }
            .reply-form{
                padding-bottom: 10px;
                padding-top: 5px;
            }
        </style>


        <script>
        $(window).load(function () {
            if(sessionStorage.getItem('anchor')){
                var offtop = sessionStorage.getItem('new_comment_location');
                $(document).scrollTop(offtop);
                window.location.hash = sessionStorage.getItem('new_comment_location');
                sessionStorage.removeItem('anchor');
            }
        });
        $.ajaxSetup({
            data: { csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
        $(document).ready(function () {
                // new-comment
                $("form.new-comment").focusin(function () {
                    $this = $(this);
                    $this.find(".submit-function-block").show();
                    $this.find(".cancel").click(function () {
                        $this.find(".submit-function-block").hide();
                        $this.find("textarea").val('');
                    });
                    // submit comment
                    $this.find(".send").click(function (e) {
                        e.preventDefault();
                        var id = $(this).data("id");
                        var content = $this.find("textarea").val();
                        if (content.length == 0){
                            alert("评论不能为空！！");
                            window.location.reload();
                            return false;
                        }
                        // use jquery post method
                        $.post("{% url 'two_comment:submit_comment' %}",{
                            id: id,
                            content: content
                        },
                        function(data) {
                            if (data['status'] == 'ok'){
                                sessionStorage.setItem('anchor', true);
                                sessionStorage.setItem('new_comment_location',
                                data['new_comment_location']);
                                window.location.reload();
                            }else {
                                alert("评论出错");
                                window.location.reload();
                                return false;
                            }
                        });
                    });
                });

            // reply-form
            $("a.reply-button").click(function () {
                $reply_button = $(this);
                if ($reply_button.hasClass('no-login')){
                    alert('登陆后才能回复');
                    return false;
                }
                var comment_id = "#comment-" + $reply_button.data('comment');
                $reply_form = $(comment_id).find(".reply-form");
                $reply_form.fadeToggle();
                $reply_form.find(".reply-cancel").click(function () {
                    $reply_form.find("textarea").val('');
                    $reply_form.fadeOut();
                });
                // submit reply
                $reply_form.find(".reply-send").click(function (e) {
                    e.preventDefault();
                    var comment = $reply_button.data('comment');
                    var author_to_id = $reply_button.data("to");
                    var content = $reply_form.find("textarea").val();
                    if (content.length == 0){
                        alert("回复不能为空！！");
                        window.location.reload();
                        return false;
                    }
                    // use jquery post method
                    $.post("{% url 'two_comment:submit_reply' %}", {
                        author_to_id: author_to_id,
                        comment_id: comment,
                        content: content
                    },function (data) {
                        if(data['status'] == 'ok'){
                            window.location.reload();
                        }else {
                            alert("回复出错");
                            window.location.reload();
                            return false;
                        }
                    });
                });
            });

            // comment favour
            $("a.favour-button").click(function (e) {
                e.preventDefault();
                $this = $(this);
                if($this.hasClass("no-login")){
                    alert("抱歉，您还没有登录喔!");
                    return false;
                }
                var id = $this.data('id');
                var action = $this.data('action');

                $.post("{% url 'two_comment:submit_favour' %}", {
                    id: id,
                    action: action
                }, function (data) {
                    if (data['status'] == 'ok'){
                        $this.data('action', action == 'favour' ? 'disfavour' : 'favour');
                        if (action == 'favour'){
                            $this.attr("style", "color: #ea6f5a");
                        }else if(action == 'disfavour'){
                            $this.attr("style", "");
                        }
                    }
                });
            });
        });
        </script>

two_comment/templates/two_comment/reply_form.html
{% load comment_tags %}
{% load bootstrap3 %}

{% get_reply_form as form %}
<form class="new-reply form" action=".">
    {% csrf_token %}
    {% bootstrap_form form %}

    <div class="reply-submit-function-block">
        <a class="btn btn-success reply-send pull-right" data-id="{{ comment.id }}" role="button">发送</a>
        <a class="btn btn-default reply-cancel pull-right" role="button">取消</a>
    </div>
</form>