confession_wall/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^list/$', views.get_confessions, name='get_confessions'),
    url(r'^detail/(?P<confession_id>\d+)/$', views.confession_detail, name='confession_detail'),
    url(r'^new//$', views.new_confession, name='new_confession'),
    url(r'^comment/$', views.submit_confession_comment, name='submit_confession_comment'),
    url(r'^reply/$', views.submit_reply_comment, name='submit_reply_comment'),
]

forum/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<post_id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^new_post/$', views.new_post, name='new_post'),
    url(r'^edit_post/(?P<post_id>\d+)/$', views.edit_post, name='edit_post'),
    url(r'^post/like/$', views.post_like, name='post_like'),
]

xiaohaishi04/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

import notifications.urls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('forum.urls', namespace='forum', app_name='forum')),
    url(r'^users/', include('users.urls', namespace='users', app_name='users')),
    url(r'^comment/', include('two_comment.urls', namespace='two_comment', app_name='two_comment')),
    url(r'^notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^confession/', include('confession_wall.urls', namespace='confession_wall', app_name='confession_wall')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

confession_wall/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Confession(models.Model):
    """
    表白墙，提供To和找某人的选项
    """
    TO = 'To'
    FIND = 'Find'
    MOTION_CHOICES = (
        (TO, 'To'),
        (FIND, 'Find')
    )
    motion = models.CharField(max_length=5, choices=MOTION_CHOICES, default=TO)
    name = models.CharField(max_length=10, blank=True, null=True)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.content

    def get_absolute_url(self):
        return reverse('confession_wall:confession_detail', args=[self.id])


class BaseComment(models.Model):
    """
    抽象出评论和回复的共同字段
    """
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True
        ordering = ['created']

    def __str__(self):
        return self.content


class Comment(BaseComment):
    confession = models.ForeignKey(Confession, related_name='comments')


class Reply(BaseComment):
    comment = models.ForeignKey(Comment, related_name='replies')

confession_wall/forms.py
from django import forms

from .models import Comment, Reply, Confession


class ConfessionForm(forms.ModelForm):
    class Meta:
        model = Confession
        fields = ['motion', 'name', 'content']
        labels = {'content': '', 'motion': '', 'name': ''}
        widgets = {'name': forms.TextInput(attrs={'placeholder': '这里写下给谁', 'class': 'confession-name'}),
                   'content': forms.Textarea(attrs={'rows': 3, 'placeholder': '写下你的表白,万一实现了呢'})}


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {'content': ''}
        widgets = {'content': forms.Textarea(attrs={'rows': 3, 'placeholder': '写下你的评论...'})}


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['content']
        labels = {'content': ''}
        widgets = {'content': forms.Textarea(attrs={'rows': 3, 'placeholder': '写下你的评论...'})}

confession_wall/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import JsonResponse

from .models import Confession, Comment
from .forms import CommentForm, ReplyForm, ConfessionForm


def get_confessions(request):
    confessions = Confession.objects.all()
    return render(request, 'confession_wall/confession_wall_list.html', {'confessions': confessions})


@login_required
@ require_POST
def new_confession(request):
    form = ConfessionForm(data=request.POST)
    if form.is_valid():
        form.save()
        return JsonResponse({'status': 'ok'})
    return JsonResponse({'status': 'ko'})


def confession_detail(request, confession_id):
    confession = get_object_or_404(Confession, id=confession_id)
    return render(request, 'confession_wall/confession_detail.html', {'confession': confession})


@login_required
@ require_POST
def submit_confession_comment(request):
    confession_id = request.POST.get('id')
    if confession_id:
        try:
            confession = Confession.objects.get(id=confession_id)
            form = CommentForm(data=request.POST)
            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.confession = confession
                new_comment.save()
                new_comment_location = '#comment-' + str(new_comment.id)
                return JsonResponse({'status': 'ok', 'new_comment_location': new_comment_location})
        except Confession.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})


@login_required
@ require_POST
def submit_reply_comment(request):
    comment_id = request.POST.get('comment_id')
    if comment_id:
        try:
            comment = Comment.objects.get(id=comment_id)
            form = ReplyForm(data=request.POST)
            if form.is_valid():
                new_reply = form.save(commit=False)
                new_reply.comment = comment
                new_reply.save()
                return JsonResponse({'status': 'ok'})
        except Comment.DoesNotExist:
            return JsonResponse({'status': 'ko'})
    return JsonResponse({'status': 'ko'})

confession_wall/templates/confession_wall/confession_detail.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load confession_tags %}


{% block header %}
    <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span>{{ confession.motion }}</span>
                    <span>{{ confession.name }}</span>
                    <span class="pull-right">{{ confession.created|date:'Y-m-j' }}</span>
                </h3>
            </div>
            <div class="panel-body">
                {{ confession.content }}
            </div>
        </div>
{% endblock %}

{% block content %}

    <div class="confession-comment-list">
        {% get_comment_form as form %}
        <!--new comment-->
        <div>
           {% if request.user.is_authenticated %}
                <form class="new-comment" action=".">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="submit-function-block">
                        <a class="btn btn-success send pull-right" data-id="{{ confession.id }}" role="button">发送</a>
                        <a class="btn btn-default cancel pull-right" role="button">取消</a>
                    </div>
                 </form>
            {% else %}
                <div class="jumbotron no-reply">
                    <h4>为防止恶意行为，请登入后发表评论，但在这里不记录任何用户信息！</h4>
                </div>
            {% endif %}
        </div>
        <!--normal-comment-list-->
        <div id="normal-comment-list" class="normal-comment-list">
            {% get_comment_list confession as comments %}
            {% if comments.count > 0 %}
                <div class="top-title">
                    <span>{{ comments.count }}</span>
                    <span>条评论</span>
                </div>
            {% endif %}

            {% for comment in comments %}
                <!--comment-->
                <div id="comment-{{ comment.id }}" class="comment">
                    <div class="comment-content">
                       <p>
                           <span>{{ forloop.counter }}</span>
                           <span>楼</span>
                       </p>
                        <p>{{ comment.content }}</p>
                    </div>
                     <div class="tool-group">
                        <span>
                            {{ comment.created|timesince }}前
                        </span>
                        <span style="margin-left: 8px">
                            <a class="reply-button text-muted {% if not request.user.is_authenticated %}no-login{% endif %}" data-comment="{{ comment.id }}">
                             <small><span class="glyphicon glyphicon-comment"></span></small>
                            </a>
                         <small>回复</small>
                        </span>
                     </div>

                     <!--normal-reply-list-->
                    {% get_reply_list comment as replies %}
                    {% if replies.count > 0 %}
                         <div class="normal-reply-list">
                        {% for reply in replies %}
                            <div id="reply-{{ reply.id }}" class="reply">
                            <div class="reply-content">
                                <p>
                                    <span>小{{ forloop.counter }}楼:</span>
                                    <span>{{ reply.content }}</span>
                                </p>
                            </div>
                            <div class="reply-tool-group">
                                <span>
                                    {{ reply.created|timesince }}前
                                </span>
                                <span style="margin-left: 8px">
                                    <a class="reply-button text-muted {% if not request.user.is_authenticated %}no-login{% endif %}" data-comment="{{ comment.id }}">
                                        <small><span class="glyphicon glyphicon-comment"></span></small>
                                    </a>
                                    <small>回复</small>
                                </span>
                            </div>
                        </div>
                        {% endfor %}
                    {% endif %}
                            <div class="reply-form">
                                {% include 'confession_wall/reply_form.html' %}
                             </div>
                        </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <style type="text/css">
         .top-title{
                padding-bottom: 18px;
                font-size: 17px;
                font-weight: 700;
                border-bottom: 1px solid #f0f0f0;
            }
        .submit-function-block{
                display: none;
        }
         .cancel, .reply-cancel{
             margin-right: 18px;
         }
        .normal-comment-list{
            margin-top: 40px;
        }
        .comment{
            padding: 20px 0 30px;
            border-bottom: 1px solid #f0f0f0;
        }
        .normal-reply-list{
                margin-top: 20px;
                padding: 5px 0 5px 20px;
                border-left: 2px solid #d9d9d9;
        }
        .reply{
                margin-bottom: 15px;
                padding-bottom: 15px;
                border-bottom: 1px dashed #f0f0f0;
        }
        .reply-form{
            display: none;
        }
         .reply-tool-group{
             font-size: 12px;
             color: #969696;
         }
         .reply-button{
             margin-left: 10px;
             color: #969696;
         }
        .reply-form{
            padding-bottom: 10px;
            padding-top: 5px;
        }
    </style>

    <script>
        $(window).load(function () {
            if(sessionStorage.getItem('anchor')){
                var offtop = sessionStorage.getItem('new_comment_location');
                alert(offtop);
                $(document).scrollTop(offtop);
                window.location.hash = sessionStorage.getItem('new_comment_location');
                sessionStorage.removeItem('anchor');
            }
        });
        $.ajaxSetup({
            data: { csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
        $(document).ready(function () {
            // new-comment
            $("form.new-comment").focusin(function () {
                $this = $(this);
                $this.find(".submit-function-block").show();
                $this.find(".cancel").click(function () {
                    $this.find(".submit-function-block").hide();
                    $this.find("textarea").val('');
                });
                // submit comment
                $this.find(".send").click(function (e) {
                    e.preventDefault();
                    var id = $(this).data("id");
                    var content = $this.find("textarea").val();
                    if (content.length == 0){
                        alert("评论不能为空！！");
                        window.location.reload();
                        return false;
                    }
                    // use jquery post method
                    $.post("{% url 'confession_wall:submit_confession_comment' %}",{
                        id: id,
                        content: content
                    },
                    function(data) {
                        if (data['status'] == 'ok'){
                            sessionStorage.setItem('anchor', true);
                            sessionStorage.setItem('new_comment_location', data['new_comment_location']);
                            window.location.reload();
                        }else {
                            alert("评论出错");
                            window.location.reload();
                            return false;
                        }
                    });
                });
            });

            // reply-form
            $("a.reply-button").click(function () {
                $reply_button = $(this);
                if ($reply_button.hasClass('no-login')){
                    alert('为防止恶意行为，请登入后执行，但在这里不记录任何用户信息！');
                    return false;
                }

                var comment_id = "#comment-" + $reply_button.data('comment');

                $reply_form = $(comment_id).find(".reply-form");
                $reply_form.fadeToggle();
                $reply_form.find(".reply-cancel").click(function () {
                    $reply_form.find("textarea").val('');
                    $reply_form.fadeOut();
                });
                // submit reply
                $reply_form.find(".reply-send").click(function (e) {
                    e.preventDefault();
                    var comment_id = $reply_button.data('comment');
                    var content = $reply_form.find("textarea").val();
                    if (content.length == 0){
                        alert("回复不能为空！！");
                        window.location.reload();
                        return false;
                    }
                    // use jquery post method
                    $.post("{% url 'confession_wall:submit_reply_comment' %}", {
                        comment_id: comment_id,
                        content: content
                    },function (data) {
                        if(data['status'] == 'ok'){
                            window.location.reload();
                        }else {
                            alert("回复出错");
                            window.location.reload();
                            return false;
                        }
                    });
                });
            });
        });
    </script>

{% endblock %}

confession_wall/templates/confession_wall/confession_wall_list.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load confession_tags %}

{% block header %}
    <h3>表白墙 <a class="btn btn-default btn-success new-confession-btn pull-right {% if not request.user.is_authenticated %}no-login{% endif %}">
        <span class="glyphicon glyphicon-pencil"></span>
        <span>写信</span>
    </a></h3>

{% endblock %}

{% block content %}
     <div>
        {% get_new_confession_form as form %}
        <form class="new-confession-form" action=".">
            {% csrf_token %}
            {% bootstrap_form form %}
            <div class="submit-function-block">
                <a class="btn btn-success send  pull-right" data-id="{{ confession.id }}" role="button">发送</a>
                <a class="btn btn-default cancel pull-right" role="button">取消</a>
            </div>
        </form>
    </div>
   {% for confession in confessions %}
         <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span>{{ confession.motion }}</span>
                    <span>{{ confession.name }}
                    <span>{{ confession.created|date:'Y-m-d' }}</span>
                    <span class="pull-right">
                        <a href="{{ confession.get_absolute_url }}" class="text-muted">
                            <span class="glyphicon glyphicon-comment"></span>
                        </a>
                    </span>
                </h3>

            </div>

            <div class="panel-body">
                {{ confession.content }}
            </div>

        </div>
   {% endfor %}

    <style type="text/css">
        .new-confession-form{
            display: none;
            margin-bottom: 80px;
        }
        .cancel{
            margin-right: 18px;
        }
    </style>

    <script>
        $.ajaxSetup({
            data: { csrfmiddlewaretoken: '{{ csrf_token }}' },
        });
        $(document).ready(function () {
            $('.new-confession-btn').click(function () {
                if ($(this).hasClass('no-login')){
                    alert('为防止恶意行为，请登入后执行，但在这里不记录任何用户信息！');
                    return false;
                }
                $new_confession_form = $('.new-confession-form');
                $new_confession_form.fadeToggle();
                $new_confession_form.find(".cancel").click(function () {
                $new_confession_form.find("textarea").val('');
                $new_confession_form.fadeOut();
            });
            // submit comment
            $new_confession_form.find(".send").click(function (e) {
                    e.preventDefault();
                    var motion = $new_confession_form.find("select").val();
                    var name = $new_confession_form.find('.confession-name').val();
                    var content = $new_confession_form.find("textarea").val();
                    if (content.length == 0){
                        alert("不能为空哦！");
                        window.location.reload();
                        return false;
                    }
                    // use jquery post method
                    $.post("{% url 'confession_wall:new_confession' %}",{
                        motion: motion,
                        name: name,
                        content: content
                    },
                    function(data) {
                        if (data['status'] == 'ok'){
                            window.location.reload();
                        }else {
                            alert("评论出错");
                            window.location.reload();
                            return false;
                        }
                    });
                });
            });
        });


    </script>

{% endblock %}

confession_wall/templates/confession_wall/reply_form.html
{% load confession_tags %}
{% load bootstrap3 %}

{% get_reply_form as form %}
<form class="new-reply form" action=".">
    {% csrf_token %}
    {% bootstrap_form form %}

    <div class="reply-submit-function-block">
        <a class="btn btn-success reply-send pull-right" data-id="{{ comment.id }}" role="button">发送</a>
        <a class="btn btn-default reply-cancel pull-right" role="button">取消</a>
    </div>
</form>